version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/golang:1.13.3
      - image: circleci/mongo:4.2.3

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make tools
      - run: make lint
      - run: make build
      - run: go test -tags integration,stress -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - codecov/upload:
          file: coverage.txt
