apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.yorkie.namespace }}
  labels:
    ## Because we only need to load balance worklaods to Yorkie service,
    ## we don't need sidecar proxy for service mesh.
    ## We are only using Istio's ingressgateway envoy for load balancing.
    # istio-injection: enabled